<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BundleResource\Pages;
use App\Models\Bundle;
use Filament\Forms;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class BundleResource extends Resource
{
    use Translatable;

    protected static ?string $model = Bundle::class;

    protected static ?string $navigationIcon = 'heroicon-o-bolt';

    protected static ?int $navigationSort = 3;


    public static function getNavigationLabel(): string
    {
        return __('bundles.label'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): ?string
    {
        return __('Products Management'); //Products Attributes Management
    }

    public static function getModelLabel(): string
    {
        return __('bundles.label'); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|null
     */
    public static function getPluralLabel(): ?string
    {
        return __('bundles.label'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return __('bundles.label'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('bundles.label');
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Tabs::make()
                    ->columnSpanFull()
                    ->tabs([
                        // General Information Tab
                        Forms\Components\Tabs\Tab::make(__('bundles.general_information'))
                            ->columnSpanFull()
                            ->schema([
                                TextInput::make('name')
                                    ->label(__('bundles.name'))
                                    ->required(),

                                TextInput::make('name_for_admin')
                                    ->label(__('bundles.name_for_admin'))
                                    ->required(),

                                Select::make('bundle_type')
                                    ->live()
                                    ->label(__('bundles.type'))
                                    ->options([
                                        'fixed_price' => __('bundles.type.fixed_price'),
                                        'buy_x_get_y' => __('bundles.type.buy_x_get_y'),
                                    ])
                                    ->required(),

                                TextInput::make('buy_x')
                                    ->live()
                                    ->label(__('bundles.buy_x'))
                                    ->numeric()
                                    ->visible(fn ($get) => $get('bundle_type') === 'buy_x_get_y'),

                                TextInput::make('get_y')
                                    ->live()
                                    ->label(__('bundles.get_y_free'))
                                    ->numeric()
                                    ->visible(fn ($get) =>
                                        $get('bundle_type') === 'buy_x_get_y' && empty($get('discount_price'))
                                    ),

                                TextInput::make('discount_price')
                                    ->live()
                                    ->label(__('bundles.discount_price'))
                                    ->numeric()
                                    ->visible(fn ($get) =>
                                        ($get('bundle_type') === 'fixed_price' || $get('bundle_type') === 'buy_x_get_y') &&
                                        empty($get('get_y'))
                                    ),

                                Select::make('products')
                                    ->searchable()
                                    ->label(__('bundles.products'))
                                    ->multiple()
                                    ->relationship('products', 'name'),
                            ]),

                        // Special Prices Tab
                        Forms\Components\Tabs\Tab::make(__('bundles.special_prices'))
                            ->schema([
                                Forms\Components\Repeater::make('specialPrices')
                                    ->label(__('bundles.special_prices'))
                                    ->relationship('specialPrices')
                                    ->columns(2)
                                    ->schema([
                                        Forms\Components\Placeholder::make('country_or_group_info')
                                            ->label(__('country_or_group_info'))
                                            ->content(__('messages.select_country_or_group'))
                                            ->columnSpanFull(),

                                        Forms\Components\Select::make('country_id')
                                            ->label(__('fields.select_country'))
                                            ->relationship('country', 'name')
                                            ->nullable()
                                            ->live()
                                            ->afterStateUpdated(fn (Forms\Set $set) => $set('country_group_id', null))
                                            ->hidden(fn (Forms\Get $get) => filled($get('country_group_id')))
                                            ->disableOptionsWhenSelectedInSiblingRepeaterItems(),

                                        Forms\Components\Select::make('country_group_id')
                                            ->label(__('fields.select_country_group'))
                                            ->relationship('countryGroup', 'name')
                                            ->preload()
                                            ->createOptionForm([
                                                Forms\Components\TextInput::make('name')
                                                    ->label(__('name'))
                                                    ->required()
                                                    ->maxLength(255),
                                                Forms\Components\Select::make('countries')
                                                    ->label(__('countries'))
                                                    ->relationship('countries', 'name')
                                                    ->multiple()
                                                    ->searchable()
                                                    ->preload(),
                                            ])
                                            ->nullable()
                                            ->live()
                                            ->afterStateUpdated(fn (Forms\Set $set) => $set('country_id', null))
                                            ->hidden(fn (Forms\Get $get) => filled($get('country_id')))
                                            ->disableOptionsWhenSelectedInSiblingRepeaterItems(),

                                        Forms\Components\Select::make('currency_id')
                                            ->label(__('fields.currency'))
                                            ->relationship('currency', 'name')
                                            ->required(),

                                        Forms\Components\TextInput::make('special_price')
                                            ->label(__('bundles.special_price'))
                                            ->numeric()
                                            ->required(),

                                        Forms\Components\TextInput::make('special_price_after_discount')
                                            ->lt('special_price')
                                            ->label(__('bundles.after_discount_price'))
                                            ->numeric()
                                            ->nullable(),
                                    ])->columnSpanFull(),
                            ]),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('bundles.name'))
                    ->searchable(),  //name_for_admin

                Tables\Columns\TextColumn::make('name_for_admin')
                    ->label(__('bundles.name_for_admin'))
                    ->searchable(),  //name_for_admin

                Tables\Columns\TextColumn::make('products.name')
                    ->label(__('bundles.products'))
                    ->placeholder('-')
                    ->limitList(2)
                    ->badge(),
                Tables\Columns\TextColumn::make('bundle_type')
                    ->badge()
                    ->label(__('bundles.type')),
                Tables\Columns\TextColumn::make('discount_price')
                    ->placeholder('-')
                    ->label(__('bundles.discount_price'))
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('buy_x')
                    ->placeholder('-')
                    ->label(__('bundles.buy_x'))
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('get_y')
                    ->label(__('bundles.get_y_free'))
                    ->numeric()
                    ->sortable()
                    ->placeholder(fn ($record) => $record->buy_x ? __('bundles.discount_price') : '-'),

                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageBundles::route('/'),
        ];
    }
}
