<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CountryGroupResource\Pages;
use App\Models\CountryGroup;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class CountryGroupResource extends Resource
{
    use Translatable;

    protected static ?string $model = CountryGroup::class;

    protected static ?string $navigationIcon = 'heroicon-o-globe-asia-australia';

    protected static ?int $navigationSort = 2;

    public static function getNavigationGroup(): ?string
    {
        return __('Countries Management'); //Products Attributes Management
    }

    public static function getNavigationLabel(): string
    {
        return __('group.label'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('group.label'); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|null
     */
    public static function getPluralLabel(): ?string
    {
        return __('group.label'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return __('group.label'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('group.label'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()->schema([
                    Forms\Components\TextInput::make('name')
                        ->label(__('name'))
                        ->required()
                        ->maxLength(255),

                    Forms\Components\Select::make('countries')
                        ->label(__('countries'))
                        ->relationship('countries', 'name')
                        ->multiple()
                        ->searchable()
                        ->preload(),
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('name'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('countries.name')
                    ->limitList(5)
                    ->label(__('countries'))
                    ->badge(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageCountryGroups::route('/'),
        ];
    }
}
