<?php

namespace App\Filament\Resources;

use App\Models\ServiceFeature;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class ServiceFeatureResource extends Resource
{
    use Translatable;

    protected static ?string $model = ServiceFeature::class;

    protected static ?string $navigationIcon = 'heroicon-o-sparkles';

    public static function getNavigationLabel(): string
    {
        return __('Service Features');
    }

    public static function getModelLabel(): string
    {
        return __('Service Feature');
    }

    public static function getPluralLabel(): ?string
    {
        return __('Service Features');
    }

    public static function getPluralModelLabel(): string
    {
        return __('Service Features');
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()->schema([
                    Forms\Components\TextInput::make('title')
                        ->label(__('Title'))
                        ->required()
                        ->live(onBlur: true)
                        ->maxLength(255),
                    Forms\Components\TextInput::make('subtitle')
                        ->label(__('Subtitle'))
                        ->maxLength(255),
                    Forms\Components\FileUpload::make('icon')
                        ->label(__('Icon'))
                        ->hint(__('Use Heroicons or any other icon library SVG')),
                ])
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('title')
                    ->label(__('Title'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('subtitle')
                    ->label(__('Subtitle'))
                    ->searchable()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\ImageColumn::make('icon')
                    ->label(__('Icon'))
                    ->circular(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('Created At'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('Updated At'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->actions([
                Tables\Actions\EditAction::make()->label(__('Edit')),
                Tables\Actions\DeleteAction::make()->label(__('Delete')),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make()->label(__('Delete Selected')),
                ]),
            ]);
    }

    public static function canCreate(): bool
    {
        return ServiceFeature::count() < 4; // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Resources\ServiceFeatureResource\Pages\ListServiceFeatures::route('/'),
            'create' => \App\Filament\Resources\ServiceFeatureResource\Pages\CreateServiceFeature::route('/create'),
            'edit' => \App\Filament\Resources\ServiceFeatureResource\Pages\EditServiceFeature::route('/{record}/edit'),
        ];
    }
}
